# Generated by Django 5.0.6 on 2024-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('num_of_prod_on_stock', models.IntegerField()),
                ('date_enrolled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
