# Generated by Django 5.0.6 on 2024-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_image_proimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
